// Fallback catalog used when no SHEET_ID is configured or the sheet can't be
// reached at build time. Ported from the design's SAMPLE().
const mk = (o) => ({
  coverH: /picture|comic|graphic/i.test((o.f_forms || []).join(' ')) ? '58px' : '82px',
  ...o,
});

export const SAMPLE = [
  mk({ id: 'shabbos', title: "I Can't Wait for Shabbos!", byline: 'by Aliza Methal; illustrated by Rivka Engel & Goldi Weiss', publisher: 'Israel Bookshop', year: '2017', pages: '24 pp.', size: '26 cm', isbn: '978-1-60091-501-7', oclc: '1560058438', lccn: '2022465406', callnum: '—', lang: 'English', series: '—', edition: '—', summary: 'A family counts down the week in rhyme, preparing the home, the food, and their hearts for the arrival of Shabbos.', subjects: ['Sabbath', 'Sabbath (Jewish law)', 'Jewish families'], f_type: 'Fiction', f_forms: ['Picture books', 'Stories in rhyme'], f_aud: 'Juvenile', f_topics: ['Sabbath', 'Jewish families'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Israel Bookshop' }),
  mk({ id: 'dovy', title: 'Dovy Learns to Share', byline: 'Malky Weinstock; illustrated by Steve Pileggi', publisher: 'Lite Boy, Inc.', year: '2017', pages: '24 pp.', size: '25 cm', isbn: '978-1-60763-241-2', oclc: '1034544260', lccn: '—', callnum: '—', lang: 'English', series: 'Lite Boy, vol. 3', edition: '—', summary: 'Dovy discovers that sharing his toys and treats brings more joy than keeping them to himself.', subjects: ['Sharing', 'Friendship', 'Jewish ethics', 'Orthodox Judaism'], f_type: 'Fiction', f_forms: ['Picture books'], f_aud: 'Juvenile', f_topics: ['Sharing', 'Friendship', 'Jewish ethics'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Lite Boy, Inc.' }),
  mk({ id: 'princess', title: 'Fit for a Princess', byline: 'by Risa Rotman; illustrated by Tova Leff', publisher: 'Hachai Publications', year: '2008', pages: '36 pp.', size: '26 cm', isbn: '978-1-929628-38-4', oclc: '234130986', lccn: '2007932113', callnum: 'PZ7.R7515 Fit 2008', lang: 'English', series: '—', edition: 'First edition', summary: "A busy princess who can't decide what to wear learns that true beauty comes from choices that make her father proud.", subjects: ['Princesses', 'Clothing and dress', 'Modesty', 'Jewish way of life', 'Jewish ethics'], f_type: 'Fiction', f_forms: ['Picture books'], f_aud: 'Primary', f_topics: ['Modesty', 'Clothing and dress', 'Jewish ethics'], f_lang: 'English', f_decade: '2000s', f_publisher: 'Hachai Publications' }),
  mk({ id: 'chanie', title: 'Chanie Goes to the Dentist', byline: 'by Rochel Levy; illustrated by Racheli David', publisher: 'Israel Bookshop', year: '2014', pages: '24 pp.', size: '27 cm', isbn: '978-1-60091-294-8', oclc: '1573516217', lccn: '2022279580', callnum: '—', lang: 'English', series: '—', edition: '—', summary: 'Chanie is nervous about her first dentist visit — until she learns there\'s nothing to fear. Told in rhyme.', subjects: ['Jewish children', 'Dentists'], f_type: 'Fiction', f_forms: ['Picture books', 'Stories in rhyme'], f_aud: 'Juvenile', f_topics: ['Jewish children', 'Dentists'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Israel Bookshop' }),
  mk({ id: 'fins', title: 'Fins, Feet, Wings, and Other Animal Things', byline: 'Yaffa Ganz; illustrated by Liat Binyamini Ariel', publisher: 'Feldheim', year: '1990', pages: '30 pp.', size: '23×24 cm', isbn: '978-0-87306-542-9', oclc: '22637163', lccn: '90049649', callnum: 'QL49 .G245 1990', lang: 'English', series: '—', edition: '—', summary: 'A unique view of animals and their place in the world according to Jewish lore and history.', subjects: ['Animals', 'Torah'], f_type: 'Nonfiction', f_forms: ['Folklore'], f_aud: 'Juvenile', f_topics: ['Animals', 'Torah'], f_lang: 'English', f_decade: '1990s', f_publisher: 'Feldheim' }),
  mk({ id: 'kosher', title: 'Kosher by Design: Kids in the Kitchen', byline: 'by Susie Fishbein; photographs by John Uher', publisher: 'ArtScroll / Mesorah', year: '2005', pages: '192 pp.', size: '26 cm', isbn: '978-1-57819-071-3', oclc: '62335885', lccn: '2014498114', callnum: 'TX724 .F495 2005', lang: 'English', series: '—', edition: '—', summary: 'Kid-friendly kosher recipes for snacks, meals, drinks, and desserts, with safety rules and kitchen basics.', subjects: ['Jewish cooking', 'Cookery, Jewish', 'Entertaining'], f_type: 'Nonfiction', f_forms: ['Cookbooks'], f_aud: 'Juvenile', f_topics: ['Jewish cooking', 'Entertaining'], f_lang: 'English', f_decade: '2000s', f_publisher: 'ArtScroll / Mesorah' }),
  mk({ id: 'flight', title: 'Flight 079', byline: 'Tzvi Aryeh Adler; illustrations Adi Katz; translation N. Davis', publisher: 'Kosher Comics for Kids', year: '2016', pages: '71 pp.', size: '31 cm', isbn: '—', oclc: '949944276', lccn: '—', callnum: '—', lang: 'English', series: '—', edition: '—', summary: 'A routine flight from Nairobi vanishes from the radar. Aboard are Rav Shaked and his sons — and a band of dangerous hijackers led by the Vulture.', subjects: ['Rabbis', 'Terrorism', 'Hijacking of aircraft'], f_type: 'Fiction', f_forms: ['Comics & Graphic novels', 'Translations'], f_aud: 'Juvenile', f_topics: ['Terrorism', 'Rabbis'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Kosher Comics for Kids' }),
  mk({ id: 'going', title: 'Going in Circles, and Other Stories', byline: 'Libby Lazewnik', publisher: 'Judaica Press', year: '2011', pages: '384 pp.', size: '22 cm', isbn: '978-1-60763-072-2', oclc: '773987987', lccn: '—', callnum: '—', lang: 'English', series: '—', edition: '—', summary: 'A collection of short stories about Jewish children navigating friendship, family, and growing up.', subjects: ['Jewish children', 'Short stories, Jewish'], f_type: 'Fiction', f_forms: ['Short stories'], f_aud: 'Juvenile', f_topics: ['Jewish children', 'Short stories, Jewish'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Judaica Press' }),
  mk({ id: 'candles', title: 'Candles in My Window', byline: 'Beth Firestone', publisher: 'Targum Press', year: '2010', pages: '167 pp.', size: '22 cm', isbn: '978-1-56871-530-8', oclc: '608627264', lccn: '2014381369', callnum: 'PZ7.F498723 C3 1990', lang: 'English', series: '—', edition: 'Revised edition', summary: "A young girl's journey of Jewish identity and belonging, told across the seasons of a formative year.", subjects: ['Jewish girls', 'Identity', 'Judaism', "Children's stories, American"], f_type: 'Fiction', f_forms: ['Realistic fiction'], f_aud: 'Juvenile', f_topics: ['Identity', 'Judaism'], f_lang: 'English', f_decade: '2010s', f_publisher: 'Targum Press' }),
  mk({ id: 'trio', title: 'Classic Trio', byline: 'Miriam L. Elias', publisher: 'Feldheim', year: '1986', pages: '468 pp.', size: '22 cm', isbn: '—', oclc: '959344473', lccn: '—', callnum: 'PZ7 E3.97 Tr 1986', lang: 'English', series: '—', edition: '—', summary: 'Three beloved novellas in one volume, following young characters through friendship, rivalry, and hope.', subjects: ['Jewish children'], f_type: 'Fiction', f_forms: ['Short stories'], f_aud: 'Juvenile', f_topics: ['Jewish children'], f_lang: 'English', f_decade: '1980s', f_publisher: 'Feldheim' }),
  mk({ id: 'galuth', title: 'Galuth Melodies: Stories for Young and Old', byline: 'Gershon Kranzler', publisher: "Merkos L'Inyonei Chinuch", year: '1965', pages: '125 pp.', size: '—', isbn: '—', oclc: '503590147', lccn: '—', callnum: 'PZ1 .K7', lang: 'English', series: '—', edition: 'Fourth edition', summary: 'A classic collection of Jewish tales of the diaspora, spanning generations and lands.', subjects: ['Tales, Jewish', 'Short stories'], f_type: 'Fiction', f_forms: ['Folklore'], f_aud: 'Juvenile', f_topics: ['Tales, Jewish'], f_lang: 'English', f_decade: '1960s', f_publisher: "Merkos L'Inyonei Chinuch" }),
  mk({ id: 'coercion', title: 'Coercion', byline: 'Ruthie Pearlman', publisher: 'Menucha Publishers', year: '2021', pages: '269 pp.', size: '24 cm', isbn: '978-1-61465-570-1', oclc: '1276809558', lccn: '—', callnum: '—', lang: 'English', series: 'Yael Reed mysteries', edition: '—', summary: 'Supersleuth Yael Reed is back — newly married as Yael Yair. Staff and students at her former boarding school are receiving blackmail notes threatening their darkest secrets. Can Yael find the blackmailers before another student is traumatized?', subjects: ['Extortion', 'Jewish religious schools', 'Detective and mystery stories', 'England'], f_type: 'Fiction', f_forms: ['Detective and mystery stories'], f_aud: 'Juvenile', f_topics: ['Extortion', 'Jewish religious schools'], f_lang: 'English', f_decade: '2020s', f_publisher: 'Menucha Publishers' }),
];
